set PrgPath=C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools 2\bin\nvcompress.exe
set PrgArgs=-fast
set InpPath=D:\Working\Homeworld\HW2_HWClassicMaps\Images_3\txt_tga
set OutPath=D:\Working\Homeworld\HW2_HWClassicMaps\Images_3\txt_dds
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_2005 Good vs Evil6.tga" "%OutPath%\HW1_2005 Good vs Evil6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_7STONES4.tga" "%OutPath%\HW1_7STONES4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_A Dolty Map4.tga" "%OutPath%\HW1_A Dolty Map4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_All Around Me6.tga" "%OutPath%\HW1_All Around Me6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Arena8.tga" "%OutPath%\HW1_Arena8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_armeddeux2_8.tga" "%OutPath%\HW1_armeddeux2_8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Ashes4.tga" "%OutPath%\HW1_Ashes4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bad Influence6.tga" "%OutPath%\HW1_Bad Influence6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bad Touch4.tga" "%OutPath%\HW1_Bad Touch4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bastage Arena6.tga" "%OutPath%\HW1_Bastage Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bends4.tga" "%OutPath%\HW1_Bends4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Blizzard Arena4.tga" "%OutPath%\HW1_Blizzard Arena4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Blizzard II6.tga" "%OutPath%\HW1_Blizzard II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Blizzard III6.tga" "%OutPath%\HW1_Blizzard III6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Blizzard spec4.tga" "%OutPath%\HW1_Blizzard spec4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Blizzard6.tga" "%OutPath%\HW1_Blizzard6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bondage4.tga" "%OutPath%\HW1_Bondage4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Brawling Corall6.tga" "%OutPath%\HW1_Brawling Corall6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Broken PomiseII(no mines)4.tga" "%OutPath%\HW1_Broken PomiseII(no mines)4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Broken WOR4.tga" "%OutPath%\HW1_Broken WOR4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Bubblicious4.tga" "%OutPath%\HW1_Bubblicious4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Cappers dream2.tga" "%OutPath%\HW1_Cappers dream2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Carrier8.tga" "%OutPath%\HW1_Carrier8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Carriers8.tga" "%OutPath%\HW1_Carriers8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Chaos4.tga" "%OutPath%\HW1_Chaos4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Choose Your Path4.tga" "%OutPath%\HW1_Choose Your Path4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Claw2.tga" "%OutPath%\HW1_Claw2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Cocoon8.tga" "%OutPath%\HW1_Cocoon8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Command and Control6.tga" "%OutPath%\HW1_Command and Control6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Conflict4.tga" "%OutPath%\HW1_Conflict4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Confusion6.tga" "%OutPath%\HW1_Confusion6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_CosmicCrunch4.tga" "%OutPath%\HW1_CosmicCrunch4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Crazy Train2.tga" "%OutPath%\HW1_Crazy Train2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_CrazyLegs8.tga" "%OutPath%\HW1_CrazyLegs8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Creations III6.tga" "%OutPath%\HW1_Creations III6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Crossbones2.tga" "%OutPath%\HW1_Crossbones2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Crystal Planet4.tga" "%OutPath%\HW1_Crystal Planet4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_crystalpalace8.tga" "%OutPath%\HW1_crystalpalace8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_CrystalPrison4.tga" "%OutPath%\HW1_CrystalPrison4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Cubic Balls6.tga" "%OutPath%\HW1_Cubic Balls6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DantesF4.tga" "%OutPath%\HW1_DantesF4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DantesFate6.tga" "%OutPath%\HW1_DantesFate6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DantesHope4.tga" "%OutPath%\HW1_DantesHope4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DantesInferno6.tga" "%OutPath%\HW1_DantesInferno6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DantesWay4.tga" "%OutPath%\HW1_DantesWay4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Darclight4.tga" "%OutPath%\HW1_Darclight4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dark Souls ll4.tga" "%OutPath%\HW1_Dark Souls ll4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dark Souls4.tga" "%OutPath%\HW1_Dark Souls4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Death Globe6.tga" "%OutPath%\HW1_Death Globe6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DerelictWorks6.tga" "%OutPath%\HW1_DerelictWorks6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_devinewind2.tga" "%OutPath%\HW1_devinewind2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Diamond6.tga" "%OutPath%\HW1_Diamond6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Diamonde6.tga" "%OutPath%\HW1_Diamonde6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Distance Wars4.tga" "%OutPath%\HW1_Distance Wars4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Distortion4.tga" "%OutPath%\HW1_Distortion4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Divine Passage II4.tga" "%OutPath%\HW1_Divine Passage II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Divine Passage III4.tga" "%OutPath%\HW1_Divine Passage III4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Divine Passage4.tga" "%OutPath%\HW1_Divine Passage4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolt Arena4.tga" "%OutPath%\HW1_Dolt Arena4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolt Hunting8.tga" "%OutPath%\HW1_Dolt Hunting8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolt Ring6.tga" "%OutPath%\HW1_Dolt Ring6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolt River6.tga" "%OutPath%\HW1_Dolt River6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolt Rush4.tga" "%OutPath%\HW1_Dolt Rush4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Doltafission4.tga" "%OutPath%\HW1_Doltafission4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolted Blizzard6.tga" "%OutPath%\HW1_Dolted Blizzard6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolterian Sphere6.tga" "%OutPath%\HW1_Dolterian Sphere6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolterious II4.tga" "%OutPath%\HW1_Dolterious II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolterious III4.tga" "%OutPath%\HW1_Dolterious III4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Dolterious4.tga" "%OutPath%\HW1_Dolterious4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DominationIII6.tga" "%OutPath%\HW1_DominationIII6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Down and Out6.tga" "%OutPath%\HW1_Down and Out6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DreadsPath6.tga" "%OutPath%\HW1_DreadsPath6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_DustCloud5.tga" "%OutPath%\HW1_DustCloud5.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Echinoid6.tga" "%OutPath%\HW1_Echinoid6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_EDy's Ring II6.tga" "%OutPath%\HW1_EDy's Ring II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_EDy's Ring III6.tga" "%OutPath%\HW1_EDy's Ring III6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_EDy's Ring6.tga" "%OutPath%\HW1_EDy's Ring6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Electric Avenue6.tga" "%OutPath%\HW1_Electric Avenue6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Empty Sphere4.tga" "%OutPath%\HW1_Empty Sphere4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_ESG WOR I 6.tga" "%OutPath%\HW1_ESG WOR I 6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_FeriilsCrossingII6.tga" "%OutPath%\HW1_FeriilsCrossingII6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_FightForBerries6.tga" "%OutPath%\HW1_FightForBerries6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Fireball4.tga" "%OutPath%\HW1_Fireball4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Flakes4.tga" "%OutPath%\HW1_Flakes4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Flat Broke4.tga" "%OutPath%\HW1_Flat Broke4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Fluffy Rocks4.tga" "%OutPath%\HW1_Fluffy Rocks4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_FoggysSmallRoom4.tga" "%OutPath%\HW1_FoggysSmallRoom4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Fools5.tga" "%OutPath%\HW1_Fools5.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Ghosty's Arena4.tga" "%OutPath%\HW1_Ghosty's Arena4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Gilgamesh8.tga" "%OutPath%\HW1_Gilgamesh8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Great Barrier Reefa6.tga" "%OutPath%\HW1_Great Barrier Reefa6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Great Barrier ReefaII spec4.tga" "%OutPath%\HW1_Great Barrier ReefaII spec4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Great Barrier ReefaII6.tga" "%OutPath%\HW1_Great Barrier ReefaII6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Great Barrier ReefaIII6.tga" "%OutPath%\HW1_Great Barrier ReefaIII6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Great Barrier ReefaIV6.tga" "%OutPath%\HW1_Great Barrier ReefaIV6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_GreatWall6.tga" "%OutPath%\HW1_GreatWall6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_half past life4.tga" "%OutPath%\HW1_half past life4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Half The Fun4.tga" "%OutPath%\HW1_Half The Fun4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Half-a-dolt6.tga" "%OutPath%\HW1_Half-a-dolt6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Hanging Gardens4.tga" "%OutPath%\HW1_Hanging Gardens4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Havocly Halved8.tga" "%OutPath%\HW1_Havocly Halved8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Helix6.tga" "%OutPath%\HW1_Helix6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_HelixF6.tga" "%OutPath%\HW1_HelixF6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_High Bounties6.tga" "%OutPath%\HW1_High Bounties6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Hiigarin Passage4.tga" "%OutPath%\HW1_Hiigarin Passage4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_HscArena6.tga" "%OutPath%\HW1_HscArena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_I Own You2.tga" "%OutPath%\HW1_I Own You2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Iam's WayII6.tga" "%OutPath%\HW1_Iam's WayII6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Infinity II6.tga" "%OutPath%\HW1_Infinity II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Infinity6.tga" "%OutPath%\HW1_Infinity6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Inverse Square6.tga" "%OutPath%\HW1_Inverse Square6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Jewel4.tga" "%OutPath%\HW1_Jewel4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Katrina's Tribute4.tga" "%OutPath%\HW1_Katrina's Tribute4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_KrakenWave4.tga" "%OutPath%\HW1_KrakenWave4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lag Ring6.tga" "%OutPath%\HW1_Lag Ring6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagg0r's Return4.tga" "%OutPath%\HW1_Lagg0r's Return4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagged Curtain6.tga" "%OutPath%\HW1_Lagged Curtain6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagger's Rush4.tga" "%OutPath%\HW1_Lagger's Rush4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lags Corral8.tga" "%OutPath%\HW1_Lags Corral8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lags crossway4.tga" "%OutPath%\HW1_Lags crossway4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lags Death Path4.tga" "%OutPath%\HW1_Lags Death Path4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagsy's Bomber Park4.tga" "%OutPath%\HW1_Lagsy's Bomber Park4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagsy's Farewell map6.tga" "%OutPath%\HW1_Lagsy's Farewell map6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lagsy's Lost Path4.tga" "%OutPath%\HW1_Lagsy's Lost Path4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LaunchPad4.tga" "%OutPath%\HW1_LaunchPad4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LCM Arena6.tga" "%OutPath%\HW1_LCM Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LEEB's Dome4.tga" "%OutPath%\HW1_LEEB's Dome4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Leet Corral6.tga" "%OutPath%\HW1_Leet Corral6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Like A Krakenn6.tga" "%OutPath%\HW1_Like A Krakenn6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Live For The Music4.tga" "%OutPath%\HW1_Live For The Music4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lost Fate6.tga" "%OutPath%\HW1_Lost Fate6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lost Souls Corral I6.tga" "%OutPath%\HW1_Lost Souls Corral I6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lost Souls Corral II6.tga" "%OutPath%\HW1_Lost Souls Corral II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lost Souls Corral III6.tga" "%OutPath%\HW1_Lost Souls Corral III6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Lost Ways4.tga" "%OutPath%\HW1_Lost Ways4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LS Arena4.tga" "%OutPath%\HW1_LS Arena4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LS Crossroads4.tga" "%OutPath%\HW1_LS Crossroads4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LunarSeige2.tga" "%OutPath%\HW1_LunarSeige2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LunarSeigeII2.tga" "%OutPath%\HW1_LunarSeigeII2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_LunarSeigeIII2.tga" "%OutPath%\HW1_LunarSeigeIII2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Maelstrom4.tga" "%OutPath%\HW1_Maelstrom4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Magic Rocks4.tga" "%OutPath%\HW1_Magic Rocks4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Malone's Race Track6.tga" "%OutPath%\HW1_Malone's Race Track6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Me Vs One2.tga" "%OutPath%\HW1_Me Vs One2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Metro Passage4.tga" "%OutPath%\HW1_Metro Passage4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Micro Masters4.tga" "%OutPath%\HW1_Micro Masters4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Minefield4.tga" "%OutPath%\HW1_Minefield4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Mobius6.tga" "%OutPath%\HW1_Mobius6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Mogwa's Last Stand III4.tga" "%OutPath%\HW1_Mogwa's Last Stand III4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Mouse Path4.tga" "%OutPath%\HW1_Mouse Path4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Multi Ring War4.tga" "%OutPath%\HW1_Multi Ring War4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Neeby Talas4.tga" "%OutPath%\HW1_Neeby Talas4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Nub Land4.tga" "%OutPath%\HW1_Nub Land4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Nublets Rule4.tga" "%OutPath%\HW1_Nublets Rule4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_OK Corral II 6.tga" "%OutPath%\HW1_OK Corral II 6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Pax WOR I 6.tga" "%OutPath%\HW1_Pax WOR I 6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Phobic Trails4.tga" "%OutPath%\HW1_Phobic Trails4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_PSA vs Two4.tga" "%OutPath%\HW1_PSA vs Two4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Rat Maze6.tga" "%OutPath%\HW1_Rat Maze6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_RedOctober4.tga" "%OutPath%\HW1_RedOctober4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Reefa Corall6.tga" "%OutPath%\HW1_Reefa Corall6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Ringed8.tga" "%OutPath%\HW1_Ringed8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_RingedNG8.tga" "%OutPath%\HW1_RingedNG8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Rock Fight4.tga" "%OutPath%\HW1_Rock Fight4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Rock Wars4.tga" "%OutPath%\HW1_Rock Wars4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_RockWars8.tga" "%OutPath%\HW1_RockWars8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Rocky Path4.tga" "%OutPath%\HW1_Rocky Path4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Roids of Pain4.tga" "%OutPath%\HW1_Roids of Pain4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_S Ring6.tga" "%OutPath%\HW1_S Ring6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Scattered Dolts4.tga" "%OutPath%\HW1_Scattered Dolts4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Scouts Pass4.tga" "%OutPath%\HW1_Scouts Pass4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Severe Arena6.tga" "%OutPath%\HW1_Severe Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_SF Corral6.tga" "%OutPath%\HW1_SF Corral6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Sigyn4.tga" "%OutPath%\HW1_Sigyn4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Simplex6.tga" "%OutPath%\HW1_Simplex6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Simplexy8.tga" "%OutPath%\HW1_Simplexy8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Skilled4.tga" "%OutPath%\HW1_Skilled4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_SlimsWeb8.tga" "%OutPath%\HW1_SlimsWeb8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_snowflake4.tga" "%OutPath%\HW1_snowflake4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Soban Arena6.tga" "%OutPath%\HW1_Soban Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Soban Battlestar6.tga" "%OutPath%\HW1_Soban Battlestar6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Soban Corral6.tga" "%OutPath%\HW1_Soban Corral6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Soban Reef6.tga" "%OutPath%\HW1_Soban Reef6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Special ED6.tga" "%OutPath%\HW1_Special ED6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Spinosaurus6.tga" "%OutPath%\HW1_Spinosaurus6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Spiral2.tga" "%OutPath%\HW1_Spiral2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Splity's Arena6.tga" "%OutPath%\HW1_Splity's Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Sputnik3.tga" "%OutPath%\HW1_Sputnik3.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Sqr Ring dusty6.tga" "%OutPath%\HW1_Sqr Ring dusty6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Squared Ring I6.tga" "%OutPath%\HW1_Squared Ring I6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Squared Ring II6.tga" "%OutPath%\HW1_Squared Ring II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Squared Ring III6.tga" "%OutPath%\HW1_Squared Ring III6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Standoff6.tga" "%OutPath%\HW1_Standoff6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Staples4.tga" "%OutPath%\HW1_Staples4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_StarLight6.tga" "%OutPath%\HW1_StarLight6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Stone Garden4.tga" "%OutPath%\HW1_Stone Garden4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Swarming Night Dreams6.tga" "%OutPath%\HW1_Swarming Night Dreams6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_t00ners Revenge6.tga" "%OutPath%\HW1_t00ners Revenge6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Talas Crosspath8.tga" "%OutPath%\HW1_Talas Crosspath8.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Talas Crossroads II2.tga" "%OutPath%\HW1_Talas Crossroads II2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Talas Way2.tga" "%OutPath%\HW1_Talas Way2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_teelan4.tga" "%OutPath%\HW1_teelan4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Tendo's Jubilee4.tga" "%OutPath%\HW1_Tendo's Jubilee4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The 2 vs 2 Map4.tga" "%OutPath%\HW1_The 2 vs 2 Map4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Ball4.tga" "%OutPath%\HW1_The Ball4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Diamond II4.tga" "%OutPath%\HW1_The Diamond II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Diamond6.tga" "%OutPath%\HW1_The Diamond6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Great Reefer4.tga" "%OutPath%\HW1_The Great Reefer4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Piller4.tga" "%OutPath%\HW1_The Piller4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Rock4.tga" "%OutPath%\HW1_The Rock4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Sand Trap4.tga" "%OutPath%\HW1_The Sand Trap4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_The Tunnel4.tga" "%OutPath%\HW1_The Tunnel4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_TheVenging6.tga" "%OutPath%\HW1_TheVenging6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_TheVengingIb6.tga" "%OutPath%\HW1_TheVengingIb6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_ThreeForAll3.tga" "%OutPath%\HW1_ThreeForAll3.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Thunderdome6.tga" "%OutPath%\HW1_Thunderdome6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Traitors Way II4.tga" "%OutPath%\HW1_Traitors Way II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Traitors Way4.tga" "%OutPath%\HW1_Traitors Way4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_TvB6.tga" "%OutPath%\HW1_TvB6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Two Vs Three5.tga" "%OutPath%\HW1_Two Vs Three5.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_ULTIMATE F-IGHTER ^0^4.tga" "%OutPath%\HW1_ULTIMATE F-IGHTER ^0^4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Unifission6.tga" "%OutPath%\HW1_Unifission6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Unifusion6.tga" "%OutPath%\HW1_Unifusion6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Us Vs Two4.tga" "%OutPath%\HW1_Us Vs Two4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Vertical WOR I6.tga" "%OutPath%\HW1_Vertical WOR I6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Victom6.tga" "%OutPath%\HW1_Victom6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Volans Fleet Wars6.tga" "%OutPath%\HW1_Volans Fleet Wars6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Vortex4.tga" "%OutPath%\HW1_Vortex4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of The Box6.tga" "%OutPath%\HW1_War of The Box6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of The Oval II6.tga" "%OutPath%\HW1_War of The Oval II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of The Oval6.tga" "%OutPath%\HW1_War of The Oval6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of the Pyramid6.tga" "%OutPath%\HW1_War of the Pyramid6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of the Ring 6.tga" "%OutPath%\HW1_War of the Ring 6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_War of the RingII 6.tga" "%OutPath%\HW1_War of the RingII 6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Watusi4.tga" "%OutPath%\HW1_Watusi4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Way of The Kraken II4.tga" "%OutPath%\HW1_Way of The Kraken II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Way of The Kraken4.tga" "%OutPath%\HW1_Way of The Kraken4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_We Own ya's4.tga" "%OutPath%\HW1_We Own ya's4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Whoo4.tga" "%OutPath%\HW1_Whoo4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Wise Passage4.tga" "%OutPath%\HW1_Wise Passage4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_WOR Cubed II4.tga" "%OutPath%\HW1_WOR Cubed II4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_WOR Cubed4.tga" "%OutPath%\HW1_WOR Cubed4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Wor Small4.tga" "%OutPath%\HW1_Wor Small4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_WOR Squared I6.tga" "%OutPath%\HW1_WOR Squared I6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_WOR Squared II6.tga" "%OutPath%\HW1_WOR Squared II6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Wormhole4.tga" "%OutPath%\HW1_Wormhole4.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_WTF Arena6.tga" "%OutPath%\HW1_WTF Arena6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Zeh Squarzy6.tga" "%OutPath%\HW1_Zeh Squarzy6.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Zip Scatt2.tga" "%OutPath%\HW1_Zip Scatt2.dds"
"%PrgPath%" %PrgArgs% "%InpPath%\HW1_Zonner Fun6.tga" "%OutPath%\HW1_Zonner Fun6.dds"
